"""post migration

Revision ID: 3b923d30bbe5
Revises: a715092749f6
Create Date: 2020-12-14 10:07:21.802589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b923d30bbe5'
down_revision = 'a715092749f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('post_name', sa.String(), nullable=False),
    sa.Column('post_description', sa.String(), nullable=False),
    sa.Column('account_active', sa.Boolean(), nullable=False),
    sa.Column('front_end', sa.Boolean(), nullable=False),
    sa.Column('back_end', sa.Boolean(), nullable=False),
    sa.Column('full_stack', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('post_github', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('profile_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_images')
    op.drop_table('post')
    # ### end Alembic commands ###
