"""added profile columns

Revision ID: bf8c368942b7
Revises: 3b923d30bbe5
Create Date: 2020-12-15 09:48:06.485516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c368942b7'
down_revision = '3b923d30bbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('back_end', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('front_end', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('full_stack', sa.Boolean(), nullable=False))
    op.alter_column('profiles', 'github',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'github',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'full_stack')
    op.drop_column('profiles', 'front_end')
    op.drop_column('profiles', 'back_end')
    # ### end Alembic commands ###
