"""admin

Revision ID: c7aaf0620e49
Revises: 16cec28096e0
Create Date: 2020-12-18 13:53:46.016962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7aaf0620e49'
down_revision = '16cec28096e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'admin')
    # ### end Alembic commands ###
